language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$AZURE_DOCKER"/sample-node:2.0.1 .;
    docker images;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    sudo apt-get install curl;
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl;
    chmod +x ./kubectl;
    sudo mv ./kubectl /usr/local/bin/kubectl;
    echo "deb https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list;
    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893;
    sudo apt-get install apt-transport-https;
    sudo apt-get update && sudo apt-get install azure-cli;
    az --version;
    az login -u "$AZURE_USERNAME" -p "$AZURE_PASSWORD"; 
    az group create --name raykorAzureResourceGroup --location eastus;
    az acr create --resource-group raykorAzureResourceGroup --name raykorAzureTest --sku Basic;
    sudo az acr login --name raykorAzureTest;
    docker push "$AZURE_DOCKER"/sample-node;
    docker images;
    fi
