version: '3'

services:
  sample-node:
    image: rtpltest/sample-node:latest
    ports:
      - 3000:3000
    deploy:
      replicas : 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure