apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-node
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sample-node
    spec:
      containers:
      - name: sample-node
        image: raykorazuretest.azurecr.io/sample-node:2.0.9
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: sample-node
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: sample-node
